// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ObtenerCPU():Promise<string>;

export function ObtenerDisco():Promise<string>;

export function ObtenerDiscoLibre():Promise<string>;

export function ObtenerDiscoUSO():Promise<string>;

export function ObtenerTotalDisco():Promise<string>;
