// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ObtenerCPU() {
  return window['go']['main']['App']['ObtenerCPU']();
}

export function ObtenerDisco() {
  return window['go']['main']['App']['ObtenerDisco']();
}

export function ObtenerDiscoLibre() {
  return window['go']['main']['App']['ObtenerDiscoLibre']();
}

export function ObtenerDiscoUSO() {
  return window['go']['main']['App']['ObtenerDiscoUSO']();
}

export function ObtenerTotalDisco() {
  return window['go']['main']['App']['ObtenerTotalDisco']();
}
